import Foundation
import XCTest
@testable import BizSimAI

/// Cross-language gate: XCTest executes the production Swift simulation formulas
/// and compares every normalized output with expectations generated by
/// backend/parity/python_golden_runner.py.
final class GoldenFormulaParityTests: XCTestCase {
    private static let relativeTolerance = 0.001 // 0.1%
    private static let absoluteTolerance = 1e-9

    private struct Fixture: Decodable { let cases: [GoldenCase] }
    private struct GoldenCase: Decodable {
        let name: String
        let round: Int
        let config: ConfigInput
        let teams: [TeamInput]
        let decisions: [String: DecisionInput]
    }
    private struct ConfigInput: Decodable {
        let randomSeed: UInt64
        let marketType: String
        let startingCash: Double
        let initialEquity: Double
        let plantCapacity: Int
        let fixedCostsPerRound: Double
        let baseCostPerUnit: Double
        let baseMarketDemand: Int
        let sharesOutstanding: Int
    }
    private struct TeamInput: Decodable {
        let id: String
        let name: String
        let cash: Double
        let inventory: Int
        let reputation: Double
        let cumulativeTQM: Double
        let equity: Double
        let debt: Double
        let sharesOutstanding: Int
        let sqRating: Double
        let imageRating: Double
        let creditRating: String
        let cumulativeInvestorScore: Double
        let roundsScored: Int
    }
    private struct DecisionInput: Decodable {
        let wholesalePrice, internetPrice, amazonPrice, privateLabelBidPrice: Double
        let privateLabelMaxUnits: Int
        let amazonAdBudget: Double
        let materialsQuality: String
        let stylingBudget: Double
        let modelsOffered: Int
        let tqmInvestment: Double
        let advertisingBudget: Double
        let celebrityEndorsement: String
        let retailOutlets: Int
        let mailInRebate: Double
        let deliveryTime: String
        let freeShippingThreshold: Double
        let tiktokBudget, instagramBudget, youtubeBudget: Double
        let influencerTier: String
        let baseWage, incentivePay, trainingHours, bestPracticesInvestment: Double
        let productionQuantity: Int
        let overtimePercent, csrInvestment, dividendsPerShare, newLoanAmount: Double
        let sharesBuyback, sharesIssued: Int
        let fulfillmentMethod: String
    }

    private struct ExpectedDocument: Decodable {
        let cases: [String: [String: ExpectedOutput]]
    }
    private struct ExpectedDemand: Decodable {
        let wholesale, internet, amazon, privateLabel, totalSold: Int
    }
    private struct ExpectedOutput: Decodable {
        let round: Int
        let revenue, costs, profit, marketShare, sqRating, cash: Double
        let inventory: Int
        let equity, debt: Double
        let sharesOutstanding: Int
        let reputation, imageRating: Double
        let creditRating: String
        let awarenessScore, eps, roe, stockPrice: Double
        let epsScore, roeScore, stockPriceScore, imageScore, creditScore, totalScore: Double
        let productionCost, marketingCost: Double
        let demand: ExpectedDemand
    }

    func testProductionSwiftFormulasMatchPythonGoldenOutputsWithinPointOnePercent() throws {
        let fixture = try decodeResource("golden_cases", as: Fixture.self)
        let expected = try decodeResource("python_expected_outputs", as: ExpectedDocument.self)
        var comparisonCount = 0

        for testCase in fixture.cases {
            let configInput = testCase.config
            let config = SessionConfiguration(
                name: testCase.name,
                totalRounds: max(testCase.round, 1),
                startingCash: configInput.startingCash,
                marketType: try XCTUnwrap(MarketType(rawValue: configInput.marketType)),
                numberOfAICompetitors: 0,
                randomSeed: configInput.randomSeed,
                fixedCostsPerRound: configInput.fixedCostsPerRound,
                baseCostPerUnit: configInput.baseCostPerUnit,
                baseMarketDemand: configInput.baseMarketDemand,
                sharesOutstanding: configInput.sharesOutstanding,
                initialEquity: configInput.initialEquity,
                plantCapacity: configInput.plantCapacity
            )
            let teams = try testCase.teams.map { input in
                TeamStatus(
                    id: try XCTUnwrap(UUID(uuidString: input.id)),
                    name: input.name,
                    cash: input.cash,
                    inventory: input.inventory,
                    reputation: input.reputation,
                    cumulativeTQM: input.cumulativeTQM,
                    equity: input.equity,
                    totalDebt: input.debt,
                    sharesOutstanding: input.sharesOutstanding,
                    sqRating: input.sqRating,
                    imageRating: input.imageRating,
                    creditRating: try XCTUnwrap(CreditRating(rawValue: input.creditRating)),
                    cumulativeInvestorScore: input.cumulativeInvestorScore,
                    roundsScored: input.roundsScored
                )
            }
            var decisions: [UUID: PlayerDecision] = [:]
            for team in teams {
                let input = try XCTUnwrap(testCase.decisions[team.name], "Missing decision for \(team.name)")
                decisions[team.id] = try makeDecision(input, teamID: team.id, round: testCase.round)
            }

            let snapshot = SimulationSnapshot(
                config: config,
                currentRound: testCase.round,
                teams: teams,
                decisions: decisions,
                previousRoundDecisions: [:],
                roundResults: [:]
            )
            let output = SimulationEngine().processRoundPure(snapshot: snapshot, decisions: decisions)
            let expectedTeams = try XCTUnwrap(expected.cases[testCase.name])

            for result in output.results {
                let update = try XCTUnwrap(output.teamUpdates.first { $0.teamId == result.teamId })
                let teamName = try XCTUnwrap(teams.first { $0.id == result.teamId }?.name)
                let golden = try XCTUnwrap(expectedTeams[teamName])
                comparisonCount += compare(result: result, update: update, expected: golden, context: "\(testCase.name)/\(teamName)")
            }
        }

        XCTAssertEqual(comparisonCount, 155, "The golden gate must cover all fields for all five fixture teams")
    }

    private func makeDecision(_ d: DecisionInput, teamID: UUID, round: Int) throws -> PlayerDecision {
        PlayerDecision(
            teamId: teamID,
            round: round,
            pricing: PricingDecision(
                wholesalePrice: d.wholesalePrice, internetPrice: d.internetPrice,
                privateLabelBidPrice: d.privateLabelBidPrice, privateLabelMaxUnits: d.privateLabelMaxUnits,
                amazonPrice: d.amazonPrice, amazonAdBudget: d.amazonAdBudget
            ),
            product: ProductDecision(
                materialsQuality: try XCTUnwrap(MaterialsQuality(rawValue: d.materialsQuality)),
                stylingBudget: d.stylingBudget, modelsOffered: d.modelsOffered, tqmInvestment: d.tqmInvestment
            ),
            marketing: MarketingDecision(
                advertisingBudget: d.advertisingBudget,
                celebrityEndorsement: try XCTUnwrap(CelebrityEndorsement(rawValue: d.celebrityEndorsement)),
                retailOutlets: d.retailOutlets, mailInRebate: d.mailInRebate,
                deliveryTime: try XCTUnwrap(DeliveryTime(rawValue: d.deliveryTime)),
                freeShippingThreshold: d.freeShippingThreshold,
                tiktokBudget: d.tiktokBudget, instagramBudget: d.instagramBudget, youtubeBudget: d.youtubeBudget,
                influencerTier: try XCTUnwrap(InfluencerTier(rawValue: d.influencerTier))
            ),
            workforce: WorkforceDecision(
                baseWage: d.baseWage, incentivePay: d.incentivePay,
                trainingHours: d.trainingHours, bestPracticesInvestment: d.bestPracticesInvestment
            ),
            production: ProductionDecision(productionQuantity: d.productionQuantity, overtimePercent: d.overtimePercent),
            finance: FinanceDecision(
                csrInvestment: d.csrInvestment, dividendsPerShare: d.dividendsPerShare,
                newLoanAmount: d.newLoanAmount, sharesBuyback: d.sharesBuyback, sharesIssued: d.sharesIssued
            ),
            fulfillmentMethod: try XCTUnwrap(FulfillmentMethod(rawValue: d.fulfillmentMethod))
        )
    }

    private func compare(result: RoundResult, update: TeamUpdate, expected e: ExpectedOutput, context: String) -> Int {
        let actual: [String: Double] = [
            "round": Double(result.round),
            "revenue": rounded(result.revenue, places: 2), "costs": rounded(result.costs, places: 2),
            "profit": rounded(result.profit, places: 2), "marketShare": rounded(result.marketShare, places: 4),
            "sqRating": rounded(result.sqRating, places: 2), "cash": rounded(result.cash, places: 2),
            "inventory": Double(result.inventory), "equity": rounded(update.equity, places: 2),
            "debt": rounded(update.totalDebt, places: 2), "sharesOutstanding": Double(update.sharesOutstanding),
            "reputation": update.reputation, "imageRating": update.imageRating,
            "awarenessScore": rounded(result.awarenessScore, places: 4), "eps": result.scorecard.eps,
            "roe": result.scorecard.roe, "stockPrice": result.scorecard.stockPrice,
            "epsScore": rounded(result.scorecard.epsScore, places: 2), "roeScore": rounded(result.scorecard.roeScore, places: 2),
            "stockPriceScore": rounded(result.scorecard.stockPriceScore, places: 2),
            "imageScore": rounded(result.scorecard.imageScore, places: 2), "creditScore": rounded(result.scorecard.creditScore, places: 2),
            "totalScore": rounded(result.scorecard.totalScore, places: 2),
            "productionCost": rounded(result.productionCosts, places: 2), "marketingCost": rounded(result.marketingCosts, places: 2),
            "demand.wholesale": Double(result.wholesaleUnitsSold), "demand.internet": Double(result.internetUnitsSold),
            "demand.amazon": Double(result.amazonUnitsSold), "demand.privateLabel": Double(result.privateLabelUnitsSold),
            "demand.totalSold": Double(result.unitsSold)
        ]
        let expected: [String: Double] = [
            "round": Double(e.round), "revenue": e.revenue, "costs": e.costs, "profit": e.profit,
            "marketShare": e.marketShare, "sqRating": e.sqRating, "cash": e.cash,
            "inventory": Double(e.inventory), "equity": e.equity, "debt": e.debt,
            "sharesOutstanding": Double(e.sharesOutstanding), "reputation": e.reputation,
            "imageRating": e.imageRating, "awarenessScore": e.awarenessScore, "eps": e.eps,
            "roe": e.roe, "stockPrice": e.stockPrice, "epsScore": e.epsScore,
            "roeScore": e.roeScore, "stockPriceScore": e.stockPriceScore, "imageScore": e.imageScore,
            "creditScore": e.creditScore, "totalScore": e.totalScore,
            "productionCost": e.productionCost, "marketingCost": e.marketingCost,
            "demand.wholesale": Double(e.demand.wholesale), "demand.internet": Double(e.demand.internet),
            "demand.amazon": Double(e.demand.amazon), "demand.privateLabel": Double(e.demand.privateLabel),
            "demand.totalSold": Double(e.demand.totalSold)
        ]

        for (field, expectedValue) in expected {
            assertParity(actual: actual[field]!, expected: expectedValue, context: "\(context)/\(field)")
        }
        XCTAssertEqual(update.creditRating.rawValue, e.creditRating, "\(context)/creditRating")
        return expected.count + 1
    }

    private func assertParity(actual: Double, expected: Double, context: String, file: StaticString = #filePath, line: UInt = #line) {
        let absoluteError = abs(actual - expected)
        let relativeError = abs(expected) <= Self.absoluteTolerance
            ? absoluteError
            : absoluteError / abs(expected)
        XCTAssertLessThanOrEqual(
            relativeError,
            Self.relativeTolerance,
            "\(context): expected \(expected), actual \(actual), relative variance \(relativeError * 100)% exceeds 0.1%",
            file: file,
            line: line
        )
    }

    private func rounded(_ value: Double, places: Int) -> Double {
        let scale = pow(10.0, Double(places))
        return (value * scale).rounded() / scale
    }

    private func decodeResource<T: Decodable>(_ name: String, as type: T.Type) throws -> T {
        let bundle = Bundle(for: Self.self)
        let url = try XCTUnwrap(
            bundle.url(forResource: name, withExtension: "json", subdirectory: "Fixtures")
                ?? bundle.url(forResource: name, withExtension: "json"),
            "Missing bundled golden resource \(name).json"
        )
        return try JSONDecoder().decode(T.self, from: Data(contentsOf: url))
    }
}
